name: Deploy Automation

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install requests module
        run: python -m pip install requests  

      - name: Ejecutar script Python
        run: |
          python - <<EOF
          import requests
          import json
          url = "https://community.cloud.automationanywhere.digital/v3/automations/deploy"
          payload = json.dumps({
            "fileId": 13252303,
            "automationName": "Prueba_API",
            "runAsUserIds": [
              639618
            ]
          })
          headers = {
            'X-Authorization': 'eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI2Mzk2MTgiLCJjbGllbnRUeXBlIjoiV0VCIiwidGVuYW50VXVpZCI6IjRiNzQxZjQ5LTJkMmItNGE3Yy05ZmM0LThlNjMwZWIyMTYxMyIsIm11bHRpcGxlTG9naW4iOmZhbHNlLCJpYXQiOjE3MjE3MDEyMjMsImV4cCI6MTcyMTcwMjQyMywiaXNzIjoiQXV0b21hdGlvbkFueXdoZXJlIiwibmFub1RpbWUiOjE1NTI3NTQ3MjM1OTIyMDV9.aH29hQTkgwt-EpLVrfc9GXMCkhl10pb5gxyGM6abzz9jnpV--gefVlWOgRxmbSpcY_F8_07r42X-XdXiZLr-VnxAjhiP0_ntlbGPom1u5Kh3qoWvqanfMlxN_wl5PjPPmv9k1Vo-4AXwqxGgyPj3pDyJ6BgA45SVH9hNGYA6k2AXyZNql70RXZ1lom8f90vySmrAuBslnMMGeD0yeeXouuob-jlplhCoZEqyOUb6ZXtsagQdE3DWc7M-AbR0OUbSyH1TW07kw5XrobLmcekcILN57tmg53VQpy9C_ml4ktxpX7Q4kzVPxIkku7dJINs1U5-EE3slf0dF0ujIfRNgSQ',
            'Content-Type': 'application/json'
          }
          response = requests.post(url, headers=headers, data=payload)
          print(response.text)
          EOF
